networks:
  dns_net:
    ipam:
      config:
        - subnet: 10.1.1.0/24

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: 10.1.1.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      - TZ=${PIHOLE_TZ}
      - WEBPASSWORD=${PIHOLE_PWD}
      - PIHOLE_DNS_=194.242.2.4
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      dns_net:
        ipv4_address: 10.1.1.3
    expose:
      - "53/tcp"
      - "53/udp"
    restart: unless-stopped
